### ISSUE TITLE
emails relating to backend queues not being sent to participants

### ISSUE THREAD

**Issue by Simon-Harris-IBM** [Simon-Harris-IBM/ObjectNetChallenge-Workflows#11]
One noticeable thing is that my SimonHarris id is receiving emails from the backend queues - which also contains the scoring. The participants are receiving emails from the front-end queue submission. I was looking at the email workflow and it looks like it should be possible to change this so the participants receive all emails, but couldn't quite figure it out. Could you take a quick look please.
 
NB: the workflow git repo has changed to: https://github.com/Simon-Harris-IBM/ObjectNetChallenge-Workflows

**Comment by thomasyu888** [comment]
https://github.com/Simon-Harris-IBM/ObjectNetChallenge-Workflows/pull/1

**Comment by Simon-Harris-IBM** [comment]
The scoring email is now sent to participants, but the Admin is still getting the start/finish emails when the job is submitted to the backend queues.

**Comment by thomasyu888** [comment]
@Simon-Harris-IBM . Added a notification email about `Submission Running on 'ObjectNet backend queue 2'!`.  

We may actually not need this email? Do participants need to know this?  Simply set the notification mask for the internal queues to not send the processing started message then you won't get the emails.

**Comment by Simon-Harris-IBM** [comment]
See #8 
Added following into .env files for backend queues to prevent sending of any emails to the admin:
`SUBMITTER_NOTIFICATION_MASK=0`
And following to fanout-queue to prevent job complete message from fanout - which was confusing as the job had really only been passed onto the execution queue, and wasn't really complete:
`SUBMITTER_NOTIFICATION_MASK=29`

Closing
