### ISSUE TITLE
Emails are sent from SimonHarris synapseid

### ISSUE THREAD

**Issue by Simon-Harris-IBM** [Simon-Harris-IBM/ObjectNetChallenge-Workflows#12]
emails to the participants are being sent from the SimonHarris synapse id which links back to my ibm email. Would be better to have a service email account that multiple people can monitor.

**Comment by thomasyu888** [comment]
Ya what you would do here is to create a synapse service account that links to a service email account.

**Comment by Simon-Harris-IBM** [comment]
Todd to see if MIT are able to create a service account with automatic forwarding

**Comment by Simon-Harris-IBM** [comment]
I've disabled the sending of start/complete emails sent from the backend queues - so the admin id will no longer receive these emails. See #8 

Do we still need a service account - is it really useful to have emails sent to a service account ?

**Comment by thomasyu888** [comment]
@Simon-Harris-IBM you don't really need a service account then since you've disabled all the emails.

**Comment by Simon-Harris-IBM** [comment]
Agreed - closing
