### ISSUE TITLE
Update main submission queue with status from backend q

### ISSUE THREAD

**Issue by Simon-Harris-IBM** [Simon-Harris-IBM/ObjectNetChallenge-Workflows#13]
@thomasyu888   thinks it should be possible to write a tool which will update the main submission q (fanout q) with details of the status etc... from the backend execution queue.

This will allow us to make the backend execution queues invisible to participants and they will only need to track progress of their submission on a single q....

**Comment by thomasyu888** [comment]
Am doing this with the current configuration.  Edit: currently only adding the scores from the internal queues onto the main queues. Will need to determine how to track the "progress" of a submission

**Comment by Simon-Harris-IBM** [comment]
#34 with fix in #35.
Closing this issue as we now have an updated status on the dashboard.
Will track one remaining issue in #30
