### ISSUE TITLE
Hide all unnecessary files from participants

### ISSUE THREAD

**Issue by Simon-Harris-IBM** [Simon-Harris-IBM/ObjectNetChallenge-Workflows#22]
Can we hide all the files under the "Files" tab which are not appropriate for participants - such as the files required to map queues onto workflows.

@thomasyu888 - I think this is possible from the UI, but is the easy way to do this in bulk ?

**Comment by thomasyu888** [comment]
@Simon-Harris-IBM,  I moved all of them here into staging: https://www.synapse.org/#!Synapse:syn21683502.  The purpose of the staging project is to house admin only files.  All of the synapse ids are the same still.  

Please also take a look at the public site.  I added a `Data` and `Resources` folder.  The `Data` folder also has permissions where only objectNet participants will be able to access.

**Comment by Simon-Harris-IBM** [comment]
Thanks Tom....
Since these files are for the workflows, will moving them break the orchestrator and/pr workflows ?

**Comment by thomasyu888** [comment]
They will not.  The orchestrator uses specific synapse ids.
