### ISSUE TITLE
Error in docker image does not produce "<submission_synid>_log.txt" file

### ISSUE THREAD

**Issue by Simon-Harris-IBM** [Simon-Harris-IBM/ObjectNetChallenge-Workflows#23]
Looks like at the moment when there is an error in the submitters docker container, then the stderr/stdout file ("<submission_synid>_log.txt" )is not uploaded.

This needs to be fixed because participants will rely on this file to debug.

**Comment by thomasyu888** [comment]
What sort of error? The file is actually uploaded, but there are some other errors that aren't caught such as:

`prediction file not generated`

Its sort of an unfortunate thing, but we are actually suppose to rely on the toil logs for debugging. (Even though they are incredibly nasty).  CWL is supposed to do all the logging for us per tool.    I have long standing agenda items to write a tool to abstract out the useful bits of CWL logging, but as you can see yourself, those log files are horrid.

**Comment by Simon-Harris-IBM** [comment]
This was a request from the MIT folks this morning. They took one look at the toil logs and said they didn't want participants seeing them - and I can't say I blame them - they are nasty - many a time over the last few weeks have I been cursing at the computer trying to figure out the logs !!!

I just tested the following scenario and I could not find the <submission_synid>_log.txt file anywhere:
 1. removed the softlink to /large/images/main-images - this means the image files will not be found
 2. submitted a docker image for evaluation.

I couldn't find the log file either under the submitterid, or my own id.

Not sure where it's going...

**Comment by thomasyu888** [comment]
I set the log files to be uploaded into the fanout queues submission log folder.  That being said, if the docker run command errors out too quickly, there won't be any logs.

1. If you remove the data, the docker run command itself will fail. No logs will be produced here.
2. You should get a log here.
