### ISSUE TITLE
Error submitting to main queue

### ISSUE THREAD

**Issue by Simon-Harris-IBM** [Simon-Harris-IBM/ObjectNetChallenge-Workflows#29]
I'm encountering an error when submitting to the main evaluation queue (ObjectNet Challenge Main submission queue (9614424)) using my non-admin id (simonh). Logs can be found here: https://www.synapse.org/#!Synapse:syn21750266 

raise SynapseMalformedEntityError("Entities of type %s must have a parentId." % type(self))

Not sure why this is happening since this queue should be using the tagged code 'v0.2' from the repo - which should be stable.

**Comment by thomasyu888** [comment]
Unfortunately. the internal queues rely on the main queue, therefore I had to update the internal queues to use the `master` branch.

Please submit everything through test for now.  @Simon-Harris-IBM ,  I think we still have some things to do before we can tag everything as stable release.

**Comment by thomasyu888** [comment]
I made a number of changes when you were gone, so we need to go through the tickets and close the ones you think can be closed.

**Comment by Simon-Harris-IBM** [comment]
ok, thanks @thomasyu888 . I'll work my way thro the tickets and test on the TEST queue....
