### ISSUE TITLE
How do I find the challengeID for ObjectNet Challenge

### ISSUE THREAD

**Issue by Simon-Harris-IBM** [Simon-Harris-IBM/ObjectNetChallenge-Workflows#31]
Need to find the challengeID of the ObjectNet challenge so I can update the teams/participants page.
`
## Registered Teams
${challengeTeams?challengeId=4339}
`

**Comment by thomasyu888** [comment]
@Simon-Harris-IBM https://www.synapse.org/#!Synapse:syn21445379/challenge/.  You can see it in the challenge tab of the live page (not staging page).  It is 4382

**Comment by Simon-Harris-IBM** [comment]
Thanks @thomasyu888
