### ISSUE TITLE
Clean up emails

### ISSUE THREAD

**Issue by Simon-Harris-IBM** [Simon-Harris-IBM/ObjectNetChallenge-Workflows#8]
Currently there are 5 or 6 emails generated per submission - because of the fan-out queue mechanism. We need to reduce the number of emails sent to participants.

**Comment by Simon-Harris-IBM** [comment]
The best way to evaluate the number of emails sent is actually to have our dry run participants tell us the number. It's harder for you to tell because you are the submitter to the main queues which is why you get all the emails

**Comment by Simon-Harris-IBM** [comment]
Looks like participants who submit will get 2 emails (from the main submission q - in progress & finished), whilst my id SimonHarris gets 3 emails (start, score & finish)...

**Comment by Simon-Harris-IBM** [comment]
Should also remove links pointing to log files for main-q submissions - since participants don't have access to these logs

**Comment by Simon-Harris-IBM** [comment]
Too many emails are sent to participants -- currently 5 for a successful submission. We should whittle these down.

Processing started on fanout q
Processing started on main q #
Workflow complete on fanout q
Workflow complete on main q #
Submission is valid message from main q

**Comment by Simon-Harris-IBM** [comment]
From @thomasyu888 :
Set this in your .env

SUBMITTER_NOTIFICATION_MASK - controls for which events notifications are sent to the submitter. The integer value is a union of these masks:

 1: send message when job has started;
 2: send message when job has completed;
 4: send message when job has failed;
 8: send message when job has been stopped by user;
 16: send message when job has timed out;
Also people won't be notified of Processing started on main q #. You get emails because you are the admin user submitting.

**Comment by Simon-Harris-IBM** [comment]
Hi @thomasyu888 - can this be customised on a per queue basis ?
For example, i might want to send the email for starting on the fanout q, but not the backend q ?

**Comment by Simon-Harris-IBM** [comment]
This is specified in the orchestrator .env so it definitely can.

**Comment by thomasyu888** [comment]
* Will most likely want to not send the workflow completed email to the fanout queue

**Comment by Simon-Harris-IBM** [comment]
Can implement this change once we have additional backend nodes and seperate out the queues/orchestrators so there is one per worker node.

**Comment by Simon-Harris-IBM** [comment]
Changed subject and content of emails
See 845270e; c0bfa9c14704c42a372710061cc9afde0c5c270f; c0bfa9c14704c42a372710061cc9afde0c5c270f

**Comment by Simon-Harris-IBM** [comment]
Added following into .env files for backend queues to prevent sending of any emails to the admin:
`
SUBMITTER_NOTIFICATION_MASK=0
`
And following to fanout-queue to prevent job complete message from fanout - which was confusing as the job had really only been passed onto the execution queue, and wasn't really complete:
`
SUBMITTER_NOTIFICATION_MASK=29
`

**Comment by Simon-Harris-IBM** [comment]
Still have to ensure links in the emails are pointing to the correct location.
Related to #18

**Comment by Simon-Harris-IBM** [comment]
Last bit of this issue is to ensure the link contained in the emails to participants points to the correct location with stdout/stderr from their docker container, plus results.json file (no toil logs or predictions.csv)

**Comment by Simon-Harris-IBM** [comment]
Submitter now receives 3 emails when:
 - submission processing started
 - submission process running (with link to user folder containing results)
 - submission complete
The admin (me) no longer receives any emails.

Closing issue
